management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: transaction-processor-group
      auto-offset-reset: latest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.anushka.transactionprocessor.dto.event.PaymentCreatedEvent
        spring.json.use.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false

server:
  port: 8081
